version: '3.7'

services:
  springboot-application:
#    build: . SpringBoot jar 이미지로 만들어서 올리는 과정이 필요!
    image: spring-application:0.2
    container_name: momsitter-app.jar
    depends_on:
      - database
    ports:
      - 8080:8080
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
      SPRING_DATASOURCE_USERNAME: sa

  database:
    image: oscarfonts/h2
    restart: always
    ports:
      - 53306:3306
    container_name: database